### PR TITLE
WIP: Fix format before save

### LINKED ISSUE #10: Rufo removes line after Rufo command run
I love this plugin. I'm facing the below problem.

[https://gyazo.com/b09a5c00494a0122e5f54b19b3c195d2](https://gyazo.com/b09a5c00494a0122e5f54b19b3c195d2)

### Operation

1. ` @test = 'test' `
2. ` :w `
3. line is gone

### vim --version

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May 28 2017 16:17:07)
MacOS X (unix) version
Included patches: 1-604
Compiled by Homebrew
```

### rufo version

```
$ bundle exec rufo -v
rufo 0.1.0
```

### .rufo

```
indent_size 2
spaces_inside_hash_brace :always
align_assignments true
align_case_when true
align_chained_calls true
```

### .vimrc

```
" Enable rufo (RUby FOrmat)
let g:rufo_auto_formatting = 1

" Enable format before saving
let g:rufo_format_before_saving = 1
```

### PR DESCRIPTION
**Pull request by splattael**
Fixes #10

### CODE REVIEW

**Comment by splattael** [comment]
@lucerion Thanks for fixing issue #10! :sparkles: 

I'll try to test your patch during this weekend :smiley:

**Comment by lucerion** [comment]
@splattael I have the same plan for this weekend too :)

**Comment by lucerion** [comment]
@splattael @tackeyy I've tested it and #10 was fixed +

* fix partial formatting

```ruby
def index
  @q = User.search(params[:q])
  @users = @q.result(distinct: true)
end
```
Select line inside `index` and try to format it with `:Rufo` command (with rufo config from #10)
* close error buffer before formatting

**Comment by splattael** [comment]
:+1: Looks good to me too!!

**Comment by lucerion** [comment]
Merged. @splattael thank you!

**Pull request merged**
